language: cpp
sudo: false
virtualenv:
  system_site_packages: true
python:
    - "3.5"
git:
    submodules: false
matrix:
  include:
    - os: osx
      osx_image: xcode7.3 # OS X 10.11.1
      compiler: clang
      before_install:
        - git submodule update --init
        - sw_vers -productVersion
        - brew update
        - brew outdated cmake || brew upgrade cmake
        - brew unlink python
        - brew install python
      install:
        - pip2 install -r python/requirements.txt
        - git submodule update --init
        - mkdir third_party/build
        - cd third_party/build
        - cmake ..
        - make -j 4
        - make install
        - cd ../..
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j 4
        - cd ..
        - ./setup.py install --user
      after_success:
        - export PYMESH_PATH=`pwd`
        - cd build
        - make all_tests
        - cd ..
        - python -c "import pymesh; pymesh.test()"

