version: 2
jobs:
    build:
        docker:
            - image: debian:sid-slim
        steps:
            - checkout
            - run: |
                apt-get update
                apt-get install -y git gcc cmake libeigen3-dev libgmp-dev libgmpxx4ldbl libumfpack5 libmpfr-dev libboost-dev libboost-thread-dev python3-dev python3-venv python3-nose python3-numpy python3-scipy python3-setuptools && apt-get clean
            - run: git checkout $CIRCLE_BRANCH
            - run: git submodule sync
            - run: git submodule update --init
            - run: python3 -m venv py_env
            - run:
                workding_directory: $CIRCLE_WORKING_DIRECTORY
                command: |
                    source py_env/bin/activate
                    mkdir -p third_party/build
                    mkdir -p build
                    pip install -r python/requirements.txt
                    cd third_party/build
                    cmake .. && make -j 4 && make install
                    cd ../../build
                    cmake .. && make
                    make all_tests

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
